name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t vtg22ug0392/web-project:latest .

      # Push the Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: docker push vtg22ug0392/web-project:latest

      # Add SSH known hosts
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "Server IP: ${{ secrets.SERVER_IP }}"
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        continue-on-error: false # This will stop if the step fails

      # Debug Server Connectivity
      - name: Debug Server Connectivity
        run: |
          echo "Attempting to connect to server..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo connected"

      # Optional: Deploy to a server (using SSH)
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull vtg22ug0392/web-project:latest
          docker stop web-project || true
          docker rm web-project || true
          docker run -d -p 80:80 --name web-project vtg22ug0392/web-project:latest
          EOF
