- name: Set up SSH for server deployment
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    
    # Debugging: Check if the key is correct
    ls -l ~/.ssh/id_rsa
    cat ~/.ssh/id_rsa
    
    ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH Connection Successful'"
    
    # Deploy Docker commands
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
      docker pull ${{ secrets.DOCKER_REPO }}/web-project:latest
      docker stop web-project || true
      docker rm web-project || true
      docker run -d -p 80:80 --name web-project ${{ secrets.DOCKER_REPO }}/web-project:latest
    EOF
