name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t vtg22ug0392/web-project:latest .

      # Push the Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: docker push vtg22ug0392/web-project:latest

      # Optional: Deploy to a server (using SSH)
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no user@hostname << 'EOF'
  docker pull ***/web-project:latest
  docker stop web-project || true
  docker rm web-project || true
  docker run -d -p 80:80 --name web-project ***/web-project:latest
EOF

